config/routes.rb
Rails.application.routes.draw do
  resources :ballots
  get 'ballot/new'

  get 'ballot/show'

  get 'ballot/edit'
  resources :ballots
  devise_for :users

    resources :ballot

end

app/models/ballot.rb
class Ballot < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/ballot_controller.rb
class BallotController < ApplicationController
  def new
    @ballot = Ballot.new
    redirect_to new_ballot_path(@ballot)
  end

  def show
   @ballot = Ballot.find_by(id: params[:id])
   if @ballot.nil?
     redirect_to action: :index
   end
  end

  def edit
    @ballot = Ballot.find(params[:id])
    @ballot.save
  end
  
  def index
    @ballots = Ballot.all
  end
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
  before_action :set_ballot, only: [:show, :edit, :update, :destroy]

  # GET /ballots
  # GET /ballots.json
  def index
    @ballots = Ballot.all
  end

  # GET /ballots/1
  # GET /ballots/1.json
  def show
  end

  # GET /ballots/new
  def new
    @ballot = Ballot.new
  end

  # GET /ballots/1/edit
  def edit
  end

  # POST /ballots
  # POST /ballots.json
  def create
    @ballot = Ballot.new(ballot_params)

    respond_to do |format|
      if @ballot.save
        format.html { redirect_to @ballot, notice: 'Ballot was successfully created.' }
        format.json { render :show, status: :created, location: @ballot }
      else
        format.html { render :new }
        format.json { render json: @ballot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ballots/1
  # PATCH/PUT /ballots/1.json
  def update
    respond_to do |format|
      if @ballot.update(ballot_params)
        format.html { redirect_to @ballot, notice: 'Ballot was successfully updated.' }
        format.json { render :show, status: :ok, location: @ballot }
      else
        format.html { render :edit }
        format.json { render json: @ballot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ballots/1
  # DELETE /ballots/1.json
  def destroy
    @ballot.destroy
    respond_to do |format|
      format.html { redirect_to ballots_url, notice: 'Ballot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ballot
      @ballot = Ballot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ballot_params
      params.require(:ballot).permit(:issue, :options)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ballot_helper.rb
module BallotHelper
end

app/helpers/ballots_helper.rb
module BallotsHelper
end

app/views/ballot/_form.html.erb
<%= form_for(@ballot) do |f| %>
  <% if @ballot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ballot.errors.count, "error") %> prohibited this ballot from being saved:</h2>
      <ul>
      <% @ballot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue %><br>
    <%= f.text_field :issue %>
  </div>
  <div class="field">
    <%= f.label :options %><br>
    <%= f.text_field :options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballot/edit.html.erb
<h1>Ballot#edit</h1>
<p>Find me in app/views/ballot/edit.html.erb</p>

app/views/ballot/index.html.erb
<h1>Listing Ballots</h1>
 
<table>
  <tr>
    <th>Issue</th>
    <th>Options</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @ballots.each do |ballot| %>
  <tr>
    <td><%= ballot.issue %></td>
    <td><%= ballot.options %></td>
    <td><%= link_to "Show", ballot %></td>
    <td><%= link_to "Edit", edit_ballot_path(ballot) %></td>
    <td><%= link_to "Remove", ballot, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>
 
<br>
 
<%= link_to "New ballot", new_ballot_path %>

app/views/ballot/new.html.erb
<h1>Ballot#new</h1>
<%= render 'form' %>
<%= link_to 'Back', ballots_path %>

app/views/ballot/show.html.erb
<h1>Ballot#show</h1>
<p>Find me in app/views/ballot/show.html.erb</p>

app/views/ballots/_form.html.erb
<%= form_for(@ballot) do |f| %>
  <% if @ballot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ballot.errors.count, "error") %> prohibited this ballot from being saved:</h2>

      <ul>
      <% @ballot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue %><br>
    <%= f.text_field :issue %>
  </div>
  <div class="field">
    <%= f.label :options %><br>
    <%= f.number_field :options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballots/edit.html.erb
<h1>Editing Ballot</h1>

<%= render 'form' %>

<%= link_to 'Show', @ballot %> |
<%= link_to 'Back', ballots_path %>

app/views/ballots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ballots</h1>

<table>
  <thead>
    <tr>
      <th>Issue</th>
      <th>Options</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ballots.each do |ballot| %>
      <tr>
        <td><%= ballot.issue %></td>
        <td><%= ballot.options %></td>
        <td><%= link_to 'Show', ballot %></td>
        <td><%= link_to 'Edit', edit_ballot_path(ballot) %></td>
        <td><%= link_to 'Destroy', ballot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ballot', new_ballot_path %>

app/views/ballots/new.html.erb
<h1>New Ballot</h1>

<%= render 'form' %>

<%= link_to 'Back', ballots_path %>

app/views/ballots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue:</strong>
  <%= @ballot.issue %>
</p>

<p>
  <strong>Options:</strong>
  <%= @ballot.options %>
</p>

<%= link_to 'Edit', edit_ballot_path(@ballot) %> |
<%= link_to 'Back', ballots_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Openvote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>